version: '3'

networks:
  todonetwork:
    driver: bridge
    name: todo-network

services:
  api:
    container_name: todo.minimal.api
    image: vitormoschetta/todo.minimal.api
    environment:            
      ConnectionStrings__DefaultConnection: "Server=todo.minimal.api.postgres;Port=5432;Database=todo-minimal-api-db;User Id=minimal;Password=Postgres@123;"
    ports:
      - 6001:6001
    networks:
      - todonetwork
    depends_on:
      - db

  db:
    container_name: todo.minimal.api.postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: minimal
      POSTGRES_PASSWORD: Postgres@123
      POSTGRES_DB: todo-minimal-api-db
    ports:
      - 5432:5432
    expose:
      - 5432    
    networks:
      - todonetwork